// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ComicService is the sole Wails bridge boundary for local comics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearRecents clears all recents and returns a fresh snapshot.
 */
export function ClearRecents(): $CancellablePromise<$models.LibraryState | null> {
    return $Call.ByID(279162531);
}

/**
 * ConsumePendingOpenPath returns and clears a path queued by OS open-with / second instance.
 * Empty string means none.
 */
export function ConsumePendingOpenPath(): $CancellablePromise<string> {
    return $Call.ByID(3490912234);
}

/**
 * GetDesktopIntegration reports Linux XDG open-with registration status.
 */
export function GetDesktopIntegration(): $CancellablePromise<$models.DesktopIntegrationStatus> {
    return $Call.ByID(1108051258);
}

/**
 * GetLibrary returns the current recents list.
 */
export function GetLibrary(): $CancellablePromise<$models.LibraryState | null> {
    return $Call.ByID(3206926331);
}

/**
 * GetPage returns the encoded page for the active comic.
 */
export function GetPage(index: number): $CancellablePromise<$models.PagePayload | null> {
    return $Call.ByID(1895050571, index);
}

/**
 * GetPageStream mints a same-origin capability URL for streaming media.
 * Images/PDF/markdown still require delivery=stream (size gate). Video/audio
 * always allowed so the reader never feeds WebKit a blob: of H.264.
 */
export function GetPageStream(index: number): $CancellablePromise<$models.PageStream | null> {
    return $Call.ByID(2657797635, index);
}

/**
 * GetRemuxedStream lossless-copies video/audio tracks into a clean MP4 (drops data
 * tracks like tmcd). Fast path when WebKit decodes H.264 briefly then fails.
 */
export function GetRemuxedStream(index: number): $CancellablePromise<$models.PageStream | null> {
    return $Call.ByID(1188587120, index);
}

/**
 * GetTranscodedStream re-encodes a video/audio page to WebM/Ogg via system ffmpeg.
 */
export function GetTranscodedStream(index: number): $CancellablePromise<$models.PageStream | null> {
    return $Call.ByID(2930947057, index);
}

/**
 * GetUpscaledStream renders a high-quality still-image viewport tile on the
 * bounded Go worker pool and returns it through the existing loopback HTTP path.
 */
export function GetUpscaledStream(req: $models.UpscaleRequest): $CancellablePromise<$models.PageStream | null> {
    return $Call.ByID(2271918455, req);
}

/**
 * InstallDesktopIntegration registers user-level .desktop + comic MIME entries on Linux.
 */
export function InstallDesktopIntegration(): $CancellablePromise<$models.DesktopIntegrationStatus> {
    return $Call.ByID(301888413);
}

/**
 * OpenArchive prompts for a supported comic archive and opens it.
 */
export function OpenArchive(): $CancellablePromise<$models.Comic | null> {
    return $Call.ByID(2421249786);
}

/**
 * OpenFolder prompts for an image folder and opens it.
 */
export function OpenFolder(): $CancellablePromise<$models.Comic | null> {
    return $Call.ByID(1828162064);
}

/**
 * OpenMedia prompts for a supported image, video, audio, PDF, or markdown file and opens it.
 */
export function OpenMedia(): $CancellablePromise<$models.Comic | null> {
    return $Call.ByID(3596181480);
}

/**
 * OpenPath opens a folder, archive, or standalone supported media file.
 * Unlike OpenRecent, a missing path does not mutate recents.
 */
export function OpenPath(path: string): $CancellablePromise<$models.Comic | null> {
    return $Call.ByID(2942930995, path);
}

/**
 * OpenRecent reopens a library path, removing it if the file is gone.
 */
export function OpenRecent(path: string): $CancellablePromise<$models.Comic | null> {
    return $Call.ByID(1821171503, path);
}

/**
 * ReleasePageStream removes an active stream capability token.
 */
export function ReleasePageStream(token: string): $CancellablePromise<void> {
    return $Call.ByID(1597265506, token);
}

/**
 * RemoveDesktopIntegration removes user-level desktop integration files on Linux.
 */
export function RemoveDesktopIntegration(): $CancellablePromise<$models.DesktopIntegrationStatus> {
    return $Call.ByID(98301510);
}

/**
 * RemoveRecents removes the given recent paths and returns a fresh snapshot.
 */
export function RemoveRecents(paths: string[] | null): $CancellablePromise<$models.LibraryState | null> {
    return $Call.ByID(2431807940, paths);
}

/**
 * SetProgress persists a zero-based page index for the active comic.
 */
export function SetProgress(index: number): $CancellablePromise<void> {
    return $Call.ByID(481786183, index);
}

/**
 * UpdateLibrarySettings updates privacy/retention settings and returns a fresh snapshot.
 */
export function UpdateLibrarySettings(settings: $models.LibrarySettings): $CancellablePromise<$models.LibraryState | null> {
    return $Call.ByID(4287182365, settings);
}
