// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Comic is the bridge-visible open-work summary.
 */
export interface Comic {
    "title": string;

    /**
     * "archive" | "folder" | "media"
     */
    "sourceType": string;
    "pageCount": number;

    /**
     * zero-based
     */
    "currentPage": number;
    "pages": PageDescriptor[] | null;
}

/**
 * LibrarySettings controls recent retention and privacy.
 */
export interface LibrarySettings {
    "saveRecents": boolean;

    /**
     * exactly 0, 7, 30, or 90; 0 means no expiry
     */
    "retentionDays": number;
}

/**
 * LibraryState is the full persisted library payload.
 */
export interface LibraryState {
    "recents": RecentComic[] | null;
    "settings": LibrarySettings;
}

/**
 * PageDescriptor is the bridge-visible per-page media metadata.
 */
export interface PageDescriptor {
    "mime": string;

    /**
     * "rpc" | "stream"
     */
    "delivery": string;
}

/**
 * PagePayload is a single page binary payload for the reader.
 */
export interface PagePayload {
    "index": number;
    "mime": string;
    "data": string | null;
}

/**
 * PageStream is the bridge-visible capability URL for oversized media.
 */
export interface PageStream {
    /**
     * relative: "/media/<token>"
     */
    "url": string;

    /**
     * opaque capability; never a path or page index
     */
    "token": string;
}

/**
 * RecentComic is one library entry shown on the landing view.
 */
export interface RecentComic {
    /**
     * canonical absolute path
     */
    "path": string;
    "title": string;

    /**
     * "archive" | "folder" | "media"
     */
    "sourceType": string;
    "pageCount": number;

    /**
     * zero-based
     */
    "currentPage": number;

    /**
     * RFC 3339 UTC
     */
    "lastOpened": string;
}
